repos:
-   repo: https://github.com/psf/black
    rev: 21.5b2
    hooks:
    -   id: black
        args: [--safe]
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.10.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==20.8b1]
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config
        args: [--application-directories, "src:."]
-   repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
-   repo: https://github.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
    -   id: flake8
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.19.1
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.8.0
    hooks:
    -   id: rst-backticks
